openapi: 3.0.0
info:
  title: Food-Delivery
  description: Food-Delivery created in Node-js, Express, MongoDB, EJS.
  version: 1.0.0
servers:
  - url: http://localhost:3300
    description: The above URL is for the hotels management.
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /login/Hotel:
    get:
      tags:
        - Hotel
      summery: Adds the hotel to the database
      description: >
        It creates the new hotel in the database
        and sees the hotel is authenticated for 
        the further optration like updating or
        adding an category and the authentication
        is in jwt
      responses:
        "200":
          description: returns an object
      security:
        - BearerAuth: []
